log_dir: /pub/afeeney/bubbleformer_logs
seed: 42

nodes: 1
devices: 1

max_epochs: 40
batch_size: 16

checkpoint_path:

use_wandb: False
wandb_tags:
  - time-window-5
  - relative-l2-loss
  - Neighbor-MoE-Small
  - poolboiling
  - AdamW-optimizer
defaults:
  - _self_
  - data_cfg: poolboiling
  - model_cfg: neighbor_moe_small
  - optim_cfg: adamw
  - scheduler_cfg: cosine_warmup